"$schema" = 'https://starship.rs/config-schema.json'

[character] # The name of the module we are configuring is "character"
success_symbol = "[ï†˜](bold #401612)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ—](bold #A6583C)"


[aws]
style = "italic #A6583C"
symbol = "îŒ½  "

[buf]
style = "italic #A6583C"
symbol = "ï’ "

[c]
style = "italic #A6583C"
symbol = "î˜ "

[conda]
style = "italic #A6583C"
symbol = "ï„Œ "

[dart]
style = "italic #A6583C"
symbol = "î˜ "

[directory]
style = "italic #A6583C"
read_only = " ï ½"
truncation_length = 3
truncation_symbol = "îŸ„"



[docker_context]
style = "italic #A6583C"
symbol = "ïŒˆ "

[elixir]
style = "italic #A6583C"
symbol = "î‰µ "

[elm]
style = "italic #A6583C"
symbol = "î˜¬ "

[git_branch]
style = "italic #A6583C"
symbol = "ï˜ "

[golang]
style = "italic #A6583C"
symbol = "î˜§ "

[haskell]
style = "italic #A6583C"
symbol = "î· "

[hg_branch]
style = "italic #A6583C"
symbol = "ï˜ "

[java]
style = "italic #A6583C"
symbol = "î‰– "

[julia]
style = "italic #A6583C"
symbol = "î˜¤ "

[memory_usage]
style = "italic #A6583C"
symbol = "ï¡š "

[nim]
style = "italic #A6583C"
symbol = "ïš¤ "

[nix_shell]
style = "italic #A6583C"
symbol = "ï‹œ "

[nodejs]
style = "italic #A6583C"
symbol = "îœ˜ "

[package]
style = "italic #A6583C"
symbol = "ï£– "

[python]
style = "italic #A6583C"
symbol = "îˆµ "

[spack]
style = "italic #A6583C"
symbol = "ğŸ…¢ "

[rust]
style = "italic #A6583C"
symbol = "î¨ "


[shell]
fish_indicator = "ïœ¹"

[username]
style_user = "white bold"
style_root = "blue bold"
format = "[$user]($style) "
disabled = true
show_always = true
