"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 1000

[character] # The name of the module we are configuring is "character"
success_symbol = "[ï†˜ ïŒ](bold #401612)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ—](bold #A6583C)"


[aws]
style = "italic #A6583C"
symbol = "îŒ½  "

[buf]
style = "italic #A6583C"
symbol = "ï’ "

[c]
style = "italic #A6583C"
symbol = "î˜ "

[conda]
style = "italic #A6583C"
symbol = "ï„Œ "

[dart]
style = "italic #A6583C"
symbol = "î˜ "

[directory]
style = "italic #A6583C"
read_only = " ï ½"
truncation_length = 1
truncation_symbol = " îŸ„"
home_symbol =  "ïŒ"



[docker_context]
style = "italic #A6583C"
symbol = "ïŒˆ "

[elixir]
style = "italic #A6583C"
symbol = "î‰µ "

[elm]
style = "italic #A6583C"
symbol = "î˜¬ "

[git_branch]
style = "italic #A6583C"
symbol = "ï˜ "

[golang]
style = "italic #A6583C"
symbol = "î˜§ "

[haskell]
style = "italic #A6583C"
symbol = "î· "

[hg_branch]
style = "italic #A6583C"
symbol = "ï˜ "

[lua]
style = "italic #A6583C"
symbol = "î˜  "

[java]
style = "italic #A6583C"
symbol = "î‰– "

[julia]
style = "italic #A6583C"
symbol = "î˜¤ "

[memory_usage]
style = "italic #A6583C"
symbol = "ï¡š "

[nim]
style = "italic #A6583C"
symbol = "ïš¤ "

[nix_shell]
style = "italic #A6583C"
symbol = "ï‹œ "

[nodejs]
detect_extensions = ["mjs", "cjs", "mts", "cts"]
style = "italic #A6583C"
symbol = "îœ˜ "

[package]
style = "italic #A6583C"
symbol = "ï£– "

[python]
style = "italic #A6583C"
symbol = "îˆµ "

[spack]
style = "italic #A6583C"
symbol = "ğŸ…¢ "

[rust]
style = "italic #A6583C"
symbol = "î¨ "


[shell]
fish_indicator = "ïœ¹"

[username]
style_user = "white bold"
style_root = "blue bold"
format = "[$user]($style) "
disabled = true
show_always = true



[custom.vim]
command = "time /T"
detect_extensions = ["vim"] # filters *.vim files
style = "italic #A6583C"
symbol = "î˜« "


[custom.js]
command = "time /T"
detect_extensions = ["js"] # filters *.js files
style = "italic #A6583C"
symbol = "ï  "

[custom.ts]
command = "time /T"
detect_extensions = ["ts"] # filters *.ts files
style = "italic #A6583C"
symbol = "ï¯¤ "

[custom.css]
command = "time /T"
detect_extensions = ["css"] # filters *.css files
style = "italic #A6583C"
symbol = "îŠ "

[custom.html]
command = "time /T"
detect_extensions = ["html"] # filters *.html files
style = "italic #A6583C"
symbol = "ï„» "

[custom.conf]
command = "time /T"
detect_extensions = ["conf"] # filters *.conf files
style = "italic #A6583C"
symbol = "î­‘ "


[custom.fish]
command = "time /T"
detect_extensions = ["fish"] # filters *.fish files
style = "italic #A6583C"
symbol = "ïœ¹ "

[custom.mask]
command = "time /T"
detect_extensions = ["mask"] # filters *.mask files
style = "italic #A6583C"
symbol = "ïŒ îˆº ï´£"

[custom.dist]
command = "time /T"
detect_extensions = ["dist_0000"] # filters *.dist_0000 files
style = "italic #A6583C"
symbol = "ïŒ îˆº"


[custom.src]
command = "time /T"
detect_folders = ["src"] # filters source folders
style = "italic #A6583C"
symbol = "î± "

[custom.gentoo]
command = "time /T"
detect_folders = ["package.mask", "package.use", "repos.conf", "package.accept_keywords"] # filters gentoo folders
style = "italic #A6583C"
symbol = "ïŒ îˆº"


