[aws]
style = "italic #A6583C"
symbol = "îŒ½  "

[buf]
style = "italic #A6583C"
symbol = "ï’ "

[c]
style = "italic #A6583C"
symbol = "î˜ "

[conda]
style = "italic #A6583C"
symbol = "ï„Œ "

[dart]
style = "italic #A6583C"
symbol = "î˜ "

[directory]
style = "italic #A6583C"
read_only = " ï ½"

[docker_context]
style = "italic #A6583C"
symbol = "ïŒˆ "

[elixir]
style = "italic #A6583C"
symbol = "î‰µ "

[elm]
style = "italic #A6583C"
symbol = "î˜¬ "

[git_branch]
style = "italic #A6583C"
symbol = "ï˜ "

[golang]
style = "italic #A6583C"
symbol = "î˜§ "

[haskell]
style = "italic #A6583C"
symbol = "î· "

[hg_branch]
style = "italic #A6583C"
symbol = "ï˜ "

[java]
style = "italic #A6583C"
symbol = "î‰– "

[julia]
style = "italic #A6583C"
symbol = "î˜¤ "

[memory_usage]
style = "italic #A6583C"
symbol = "ï¡š "

[nim]
style = "italic #A6583C"
symbol = "ïš¤ "

[nix_shell]
style = "italic #A6583C"
symbol = "ï‹œ "

[nodejs]
style = "italic #A6583C"
symbol = "îœ˜ "

[package]
style = "italic #A6583C"
symbol = "ï£– "

[python]
style = "italic #A6583C"
symbol = "îˆµ "

[spack]
style = "italic #A6583C"
symbol = "ğŸ…¢ "

[rust]
style = "italic #A6583C"
symbol = "î¨ "


